In [2]:
import tensorflow as tf
from data_proccessing import image_size, labels
from tensorflow.keras import datasets, layers, models, losses


alex_model = models.Sequential()
alex_model.add(layers.Resizing(224, 224, interpolation="bilinear", input_shape=(image_size, image_size, 3)))
alex_model.add(layers.Conv2D(96, 11, strides=4, padding='same'))
alex_model.add(layers.Lambda(tf.nn.local_response_normalization))
alex_model.add(layers.Activation('relu'))
alex_model.add(layers.MaxPooling2D(3, strides=2))
alex_model.add(layers.Conv2D(256, 5, strides=4, padding='same'))
alex_model.add(layers.Lambda(tf.nn.local_response_normalization))
alex_model.add(layers.Activation('relu'))
alex_model.add(layers.MaxPooling2D(3, strides=2))
alex_model.add(layers.Conv2D(384, 3, strides=4, padding='same'))
alex_model.add(layers.Activation('relu'))
alex_model.add(layers.Conv2D(384, 3, strides=4, padding='same'))
alex_model.add(layers.Activation('relu'))
alex_model.add(layers.Conv2D(256, 3, strides=4, padding='same'))
alex_model.add(layers.Activation('relu'))
alex_model.add(layers.Flatten())
alex_model.add(layers.Dense(4096, activation='relu'))
alex_model.add(layers.Dropout(0.5))
alex_model.add(layers.Dense(4096, activation='relu'))
alex_model.add(layers.Dropout(0.5))
alex_model.add(layers.Dense(num_classes, activation='softmax'))
alex_model.summary()

Found 4620 validated image filenames belonging to 15 classes.
Found 1155 validated image filenames belonging to 15 classes.


/Users/abigail/Documents/adl/data_proccessing.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_new = pd.concat([df_new, data_entry[data_entry[l]==1][:500]], ignore_index=True)


[[[[0.03529412 0.03529412 0.03529412]
   [0.03529412 0.03529412 0.03529412]
   [0.03529412 0.03529412 0.03529412]
   ...
   [0.08627451 0.08627451 0.08627451]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  [[0.03529412 0.03529412 0.03529412]
   [0.04313726 0.04313726 0.04313726]
   [0.03529412 0.03529412 0.03529412]
   ...
   [0.08627451 0.08627451 0.08627451]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  [[0.03529412 0.03529412 0.03529412]
   [0.03529412 0.03529412 0.03529412]
   [0.03529412 0.03529412 0.03529412]
   ...
   [0.08235294 0.08235294 0.08235294]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  ...

  [[0.02352941 0.02352941 0.02352941]
   [0.02352941 0.02352941 0.02352941]
   [0.01960784 0.01960784 0.01960784]
   ...
   [0.13725491 0.13725491 0.13725491]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  [[0.02745098 0.02745098 0.02745098]
   [0.0

/Users/abigail/Documents/adl/venv/lib/python3.10/site-packages/keras/src/layers/preprocessing/tf_data_layer.py:18: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ resizing (Resizing)             │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 56, 56, 96)     │        34,944 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda (Lambda)                 │ (None, 56, 56, 96)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 56, 56, 96)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 27, 27, 96)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 7, 7, 256)      │       614,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda_1 (Lambda)               │ (None, 7, 7, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 7, 7, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 3, 3, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 1, 1, 384)      │       885,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_2 (Activation)       │ (None, 1, 1, 384)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 1, 1, 384)      │     1,327,488 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_3 (Activation)       │ (None, 1, 1, 384)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 1, 1, 256)      │       884,992 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_4 (Activation)       │ (None, 1, 1, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 4096)           │     1,052,672 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 4096)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4096)           │    16,781,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 4096)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 15)             │        61,455 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,642,639 (82.56 MB)

 Trainable params: 21,642,639 (82.56 MB)

 Non-trainable params: 0 (0.00 B)

In [17]:
alex_model.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics=['AUC','Precision','Recall', 'Accuracy'])

In [18]:
from data_proccessing import train_gen, valid_gen, X_val, y_val
alexnet1 = alex_model.fit(train_gen,
              validation_data = valid_gen,
              epochs = 10,) # 95 min

y_pred = alex_model.predict(X_val)

Epoch 1/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 118s 782ms/step - AUC: 0.5885 - Precision: 0.0000e+00 - Recall: 0.0000e+00 - loss: 0.3767 - val_AUC: 0.6069 - val_Precision: 0.0000e+00 - val_Recall: 0.0000e+00 - val_loss: 0.3424
Epoch 2/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 101s 669ms/step - AUC: 0.5954 - Precision: 0.0000e+00 - Recall: 0.0000e+00 - loss: 0.3421 - val_AUC: 0.6128 - val_Precision: 0.0000e+00 - val_Recall: 0.0000e+00 - val_loss: 0.3401
Epoch 3/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 101s 669ms/step - AUC: 0.6068 - Precision: 0.0000e+00 - Recall: 0.0000e+00 - loss: 0.3381 - val_AUC: 0.6123 - val_Precision: 0.0000e+00 - val_Recall: 0.0000e+00 - val_loss: 0.3395
Epoch 4/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 101s 669ms/step - AUC: 0.6082 - Precision: 0.0000e+00 - Recall: 0.0000e+00 - loss: 0.3386 - val_AUC: 0.6060 - val_Precision: 0.0000e+00 - val_Recall: 0.0000e+00 - val_loss: 0.3406
Epoch 5/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 99s 655ms/step - AUC: 0.6067 - Precision: 0.0000e+00 - Recall: 0.0000e+00 - loss

In [19]:


evaluation_results = alex_model.evaluate(valid_gen)
print("AUC:", evaluation_results[0])
print("Precision:", evaluation_results[1])
print("Recall:", evaluation_results[2])
print("Accuracy", evaluation_results[3])
print("Loss", evaluation_results[4])

1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step - AUC: 0.6146 - Precision: 0.0000e+00 - Recall: 0.0000e+00 - loss: 0.3388
AUC: 0.33878904581069946
Precision: 0.6145837306976318
Recall: 0.0
Loss 0.0
Accuracy 0.0


In [20]:
alex_model.save('models/alexnet.h5')

In [7]:

from tensorflow.keras import models
from data_proccessing import valid_gen

model = models.load_model('models/alexnet.keras')
evaluation_results = alex_model.evaluate(valid_gen)

print("AUC:", evaluation_results[0])
print("Precision:", evaluation_results[1])
print("Recall:", evaluation_results[2])
print("Accuracy", evaluation_results[3])
print("Loss", evaluation_results[4])

TypeError: <class 'keras.src.models.sequential.Sequential'> could not be deserialized properly. Please ensure that components that are Python object instances (layers, models, etc.) returned by `get_config()` are explicitly deserialized in the model's `from_config()` method.

config={'module': 'keras', 'class_name': 'Sequential', 'config': {'name': 'sequential_7', 'trainable': True, 'dtype': 'float32', 'layers': [{'module': 'keras.layers', 'class_name': 'InputLayer', 'config': {'batch_shape': [None, 224, 224, 3], 'dtype': 'float32', 'sparse': False, 'name': 'input_layer_3'}, 'registered_name': None}, {'module': 'keras.layers', 'class_name': 'Resizing', 'config': {'name': 'resizing_3', 'trainable': True, 'dtype': 'float32', 'height': 224, 'width': 224, 'interpolation': 'bilinear', 'crop_to_aspect_ratio': False, 'data_format': 'channels_last'}, 'registered_name': None, 'build_config': {'input_shape': [None, 224, 224, 3]}}, {'module': 'keras.layers', 'class_name': 'Conv2D', 'config': {'name': 'conv2d_15', 'trainable': True, 'dtype': 'float32', 'filters': 96, 'kernel_size': [11, 11], 'strides': [4, 4], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 224, 224, 3]}}, {'module': 'keras.layers', 'class_name': 'Lambda', 'config': {'name': 'lambda_6', 'trainable': True, 'dtype': 'float32', 'function': {'module': 'builtins', 'class_name': 'function', 'config': 'lrn', 'registered_name': 'function'}, 'arguments': {}}, 'registered_name': None, 'build_config': {'input_shape': [None, 56, 56, 96]}}, {'module': 'keras.layers', 'class_name': 'Activation', 'config': {'name': 'activation_15', 'trainable': True, 'dtype': 'float32', 'activation': 'relu'}, 'registered_name': None, 'build_config': {'input_shape': [None, 56, 56, 96]}}, {'module': 'keras.layers', 'class_name': 'MaxPooling2D', 'config': {'name': 'max_pooling2d_6', 'trainable': True, 'dtype': 'float32', 'pool_size': [3, 3], 'padding': 'valid', 'strides': [2, 2], 'data_format': 'channels_last'}, 'registered_name': None, 'build_config': {'input_shape': [None, 56, 56, 96]}}, {'module': 'keras.layers', 'class_name': 'Conv2D', 'config': {'name': 'conv2d_16', 'trainable': True, 'dtype': 'float32', 'filters': 256, 'kernel_size': [5, 5], 'strides': [4, 4], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 27, 27, 96]}}, {'module': 'keras.layers', 'class_name': 'Lambda', 'config': {'name': 'lambda_7', 'trainable': True, 'dtype': 'float32', 'function': {'module': 'builtins', 'class_name': 'function', 'config': 'lrn', 'registered_name': 'function', 'shared_object_id': 4873241504}, 'arguments': {}}, 'registered_name': None, 'build_config': {'input_shape': [None, 7, 7, 256]}}, {'module': 'keras.layers', 'class_name': 'Activation', 'config': {'name': 'activation_16', 'trainable': True, 'dtype': 'float32', 'activation': 'relu'}, 'registered_name': None, 'build_config': {'input_shape': [None, 7, 7, 256]}}, {'module': 'keras.layers', 'class_name': 'MaxPooling2D', 'config': {'name': 'max_pooling2d_7', 'trainable': True, 'dtype': 'float32', 'pool_size': [3, 3], 'padding': 'valid', 'strides': [2, 2], 'data_format': 'channels_last'}, 'registered_name': None, 'build_config': {'input_shape': [None, 7, 7, 256]}}, {'module': 'keras.layers', 'class_name': 'Conv2D', 'config': {'name': 'conv2d_17', 'trainable': True, 'dtype': 'float32', 'filters': 384, 'kernel_size': [3, 3], 'strides': [4, 4], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 3, 3, 256]}}, {'module': 'keras.layers', 'class_name': 'Activation', 'config': {'name': 'activation_17', 'trainable': True, 'dtype': 'float32', 'activation': 'relu'}, 'registered_name': None, 'build_config': {'input_shape': [None, 1, 1, 384]}}, {'module': 'keras.layers', 'class_name': 'Conv2D', 'config': {'name': 'conv2d_18', 'trainable': True, 'dtype': 'float32', 'filters': 384, 'kernel_size': [3, 3], 'strides': [4, 4], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 1, 1, 384]}}, {'module': 'keras.layers', 'class_name': 'Activation', 'config': {'name': 'activation_18', 'trainable': True, 'dtype': 'float32', 'activation': 'relu'}, 'registered_name': None, 'build_config': {'input_shape': [None, 1, 1, 384]}}, {'module': 'keras.layers', 'class_name': 'Conv2D', 'config': {'name': 'conv2d_19', 'trainable': True, 'dtype': 'float32', 'filters': 256, 'kernel_size': [3, 3], 'strides': [4, 4], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 1, 1, 384]}}, {'module': 'keras.layers', 'class_name': 'Activation', 'config': {'name': 'activation_19', 'trainable': True, 'dtype': 'float32', 'activation': 'relu'}, 'registered_name': None, 'build_config': {'input_shape': [None, 1, 1, 256]}}, {'module': 'keras.layers', 'class_name': 'Flatten', 'config': {'name': 'flatten_3', 'trainable': True, 'dtype': 'float32', 'data_format': 'channels_last'}, 'registered_name': None, 'build_config': {'input_shape': [None, 1, 1, 256]}}, {'module': 'keras.layers', 'class_name': 'Dense', 'config': {'name': 'dense_9', 'trainable': True, 'dtype': 'float32', 'units': 4096, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 256]}}, {'module': 'keras.layers', 'class_name': 'Dropout', 'config': {'name': 'dropout_6', 'trainable': True, 'dtype': 'float32', 'rate': 0.5, 'seed': None, 'noise_shape': None}, 'registered_name': None}, {'module': 'keras.layers', 'class_name': 'Dense', 'config': {'name': 'dense_10', 'trainable': True, 'dtype': 'float32', 'units': 4096, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 4096]}}, {'module': 'keras.layers', 'class_name': 'Dropout', 'config': {'name': 'dropout_7', 'trainable': True, 'dtype': 'float32', 'rate': 0.5, 'seed': None, 'noise_shape': None}, 'registered_name': None}, {'module': 'keras.layers', 'class_name': 'Dense', 'config': {'name': 'dense_11', 'trainable': True, 'dtype': 'float32', 'units': 15, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'registered_name': None, 'build_config': {'input_shape': [None, 4096]}}], 'build_input_shape': [None, 224, 224, 3]}, 'registered_name': None, 'build_config': {'input_shape': [None, 224, 224, 3]}, 'compile_config': {'optimizer': 'adam', 'loss': 'binary_crossentropy', 'loss_weights': None, 'metrics': ['AUC', 'Precision', 'Recall'], 'weighted_metrics': None, 'run_eagerly': False, 'steps_per_execution': 1, 'jit_compile': False}}.

Exception encountered: <class 'keras.src.layers.core.lambda_layer.Lambda'> could not be deserialized properly. Please ensure that components that are Python object instances (layers, models, etc.) returned by `get_config()` are explicitly deserialized in the model's `from_config()` method.

config={'module': 'keras.layers', 'class_name': 'Lambda', 'config': {'name': 'lambda_6', 'trainable': True, 'dtype': 'float32', 'function': {'module': 'builtins', 'class_name': 'function', 'config': 'lrn', 'registered_name': 'function'}, 'arguments': {}}, 'registered_name': None, 'build_config': {'input_shape': [None, 56, 56, 96]}}.

Exception encountered: Could not locate function 'lrn'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'builtins', 'class_name': 'function', 'config': 'lrn', 'registered_name': 'function'}