In [1]:
from tensorflow.keras.applications import DenseNet121
from data_proccessing import image_size, labels
import tensorflow as tf

dnet = DenseNet121(
        input_shape=(image_size, image_size, 3),
        weights='imagenet',
        include_top=False
    )
dnet.trainable = True

dnet_model = tf.keras.Sequential([
    dnet,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(len(labels), activation='sigmoid')])

dnet_model.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics=['AUC','Precision','Recall'])

Found 4620 validated image filenames belonging to 15 classes.
Found 1155 validated image filenames belonging to 15 classes.


/Users/abigail/Documents/adl/data_proccessing.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_new = pd.concat([df_new, data_entry[data_entry[l]==1][:500]], ignore_index=True)


[[[[0.01960784 0.01960784 0.01960784]
   [0.01960784 0.01960784 0.01960784]
   [0.02745098 0.02745098 0.02745098]
   ...
   [0.16078432 0.16078432 0.16078432]
   [0.14901961 0.14901961 0.14901961]
   [0.15686275 0.15686275 0.15686275]]

  [[0.03137255 0.03137255 0.03137255]
   [0.04705883 0.04705883 0.04705883]
   [0.03529412 0.03529412 0.03529412]
   ...
   [0.18431373 0.18431373 0.18431373]
   [0.17254902 0.17254902 0.17254902]
   [0.16862746 0.16862746 0.16862746]]

  [[0.02745098 0.02745098 0.02745098]
   [0.02745098 0.02745098 0.02745098]
   [0.03529412 0.03529412 0.03529412]
   ...
   [0.18039216 0.18039216 0.18039216]
   [0.16862746 0.16862746 0.16862746]
   [0.1764706  0.1764706  0.1764706 ]]

  ...

  [[0.6156863  0.6156863  0.6156863 ]
   [0.61960787 0.61960787 0.61960787]
   [0.6745098  0.6745098  0.6745098 ]
   ...
   [0.7490196  0.7490196  0.7490196 ]
   [0.73333335 0.73333335 0.73333335]
   [0.7372549  0.7372549  0.7372549 ]]

  [[0.6156863  0.6156863  0.6156863 ]
   [0.6

In [2]:
from data_proccessing import train_gen, valid_gen, X_val, y_val

history = dnet_model.fit(train_gen,
              validation_data = valid_gen,
              epochs = 10,)

y_pred = dnet_model.predict(X_val)

Epoch 1/10


/Users/abigail/Documents/adl/venv/lib/python3.10/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


145/145 ━━━━━━━━━━━━━━━━━━━━ 657s 4s/step - AUC: 0.6062 - Precision: 0.1347 - Recall: 0.0509 - loss: 0.3946 - val_AUC: 0.5513 - val_Precision: 0.0000e+00 - val_Recall: 0.0000e+00 - val_loss: 0.3717
Epoch 2/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 576s 4s/step - AUC: 0.6869 - Precision: 0.4437 - Recall: 0.0121 - loss: 0.3284 - val_AUC: 0.5643 - val_Precision: 0.1399 - val_Recall: 0.0212 - val_loss: 0.3964
Epoch 3/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 628s 4s/step - AUC: 0.7077 - Precision: 0.5141 - Recall: 0.0346 - loss: 0.3176 - val_AUC: 0.5959 - val_Precision: 0.1489 - val_Recall: 0.1248 - val_loss: 0.4631
Epoch 4/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 634s 4s/step - AUC: 0.7281 - Precision: 0.5685 - Recall: 0.0503 - loss: 0.3134 - val_AUC: 0.6420 - val_Precision: 0.4175 - val_Recall: 0.0223 - val_loss: 0.3476
Epoch 5/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 634s 4s/step - AUC: 0.7429 - Precision: 0.5748 - Recall: 0.0567 - loss: 0.3083 - val_AUC: 0.6838 - val_Precision: 0.4922 - val_Recall: 0.0326 - val_loss: 0.333

2024-04-14 18:39:56.478641: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:450] ShuffleDatasetV3:2: Filling up shuffle buffer (this may take a while): 3 of 8
2024-04-14 18:39:59.141786: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:480] Shuffle buffer filled.


145/145 ━━━━━━━━━━━━━━━━━━━━ 809s 4s/step - AUC: 0.7635 - Precision: 0.5545 - Recall: 0.0726 - loss: 0.2989 - val_AUC: 0.5777 - val_Precision: 0.1571 - val_Recall: 0.0171 - val_loss: 0.3850
Epoch 9/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 579s 4s/step - AUC: 0.7678 - Precision: 0.6064 - Recall: 0.0959 - loss: 0.2992 - val_AUC: 0.6932 - val_Precision: 0.6857 - val_Recall: 0.0124 - val_loss: 0.3257
Epoch 10/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 2452s 17s/step - AUC: 0.7791 - Precision: 0.6271 - Recall: 0.1104 - loss: 0.2946 - val_AUC: 0.6976 - val_Precision: 0.5735 - val_Recall: 0.0202 - val_loss: 0.3249
37/37 ━━━━━━━━━━━━━━━━━━━━ 29s 754ms/step


In [7]:
import numpy as np
for label, p_count, t_count in zip(labels,
                                     100 * np.mean(y_pred, 0),
                                     100 * np.mean(y_val, 0)):
    print('%s: actual: %2.2f%%, predicted: %2.2f%%' % (label, t_count, p_count))

Atelectasis: actual: 16.54%, predicted: 18.59%
Cardiomegaly: actual: 9.09%, predicted: 6.88%
Consolidation: actual: 9.78%, predicted: 12.95%
Edema: actual: 9.44%, predicted: 4.35%
Effusion: actual: 17.66%, predicted: 14.76%
Emphysema: actual: 9.09%, predicted: 8.40%
Fibrosis: actual: 8.92%, predicted: 7.82%
Hernia: actual: 3.98%, predicted: 10.18%
Infiltration: actual: 25.54%, predicted: 15.74%
Mass: actual: 9.96%, predicted: 18.48%
No Finding: actual: 8.66%, predicted: 6.00%
Nodule: actual: 10.39%, predicted: 11.00%
Pleural_Thickening: actual: 8.40%, predicted: 9.52%
Pneumonia: actual: 8.92%, predicted: 6.51%
Pneumothorax: actual: 10.82%, predicted: 8.67%


In [9]:

evaluation_results = dnet_model.evaluate(valid_gen)
print("AUC:", evaluation_results[0])
print("Precision:", evaluation_results[1])
print("Recall:", evaluation_results[2])
print("Loss", evaluation_results[2])

1/1 ━━━━━━━━━━━━━━━━━━━━ 42s 42s/step - AUC: 0.6976 - Precision: 0.5735 - Recall: 0.0202 - loss: 0.3249
AUC: 0.32492390275001526
Precision: 0.6976433396339417
Recall: 0.5735294222831726
Loss 0.5735294222831726


In [3]:
dnet_model.save('models/densNet.keras')