In [1]:
from tensorflow.keras.applications import InceptionV3
from data_proccessing import image_size, labels
import tensorflow as tf

inception = InceptionV3(
    input_shape=(image_size, image_size, 3),
    weights='imagenet',
    include_top=False
)
inception.trainable = True

inception_model = tf.keras.Sequential([
    inception,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(len(labels), activation='sigmoid')
])

inception_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['AUC','Precision','Recall', 'Accuracy']
)

d:\adl\data_proccessing.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_new = pd.concat([df_new, data_entry[data_entry[l]==1][:500]], ignore_index=True)


Found 4620 validated image filenames belonging to 15 classes.
Found 1155 validated image filenames belonging to 15 classes.
[[[[0.08627451 0.08627451 0.08627451]
   [0.07843138 0.07843138 0.07843138]
   [0.07843138 0.07843138 0.07843138]
   ...
   [0.09019608 0.09019608 0.09019608]
   [0.10588236 0.10588236 0.10588236]
   [0.09803922 0.09803922 0.09803922]]

  [[0.08235294 0.08235294 0.08235294]
   [0.08235294 0.08235294 0.08235294]
   [0.07843138 0.07843138 0.07843138]
   ...
   [0.09019608 0.09019608 0.09019608]
   [0.09411766 0.09411766 0.09411766]
   [0.09019608 0.09019608 0.09019608]]

  [[0.08235294 0.08235294 0.08235294]
   [0.08627451 0.08627451 0.08627451]
   [0.08235294 0.08235294 0.08235294]
   ...
   [0.08627451 0.08627451 0.08627451]
   [0.09411766 0.09411766 0.09411766]
   [0.09411766 0.09411766 0.09411766]]

  ...

  [[0.60784316 0.60784316 0.60784316]
   [0.57254905 0.57254905 0.57254905]
   [0.5686275  0.5686275  0.5686275 ]
   ...
   [0.09803922 0.09803922 0.09803922]

In [2]:
from data_proccessing import train_gen, valid_gen, X_val, y_val

history = inception_model.fit(
    train_gen,
    validation_data=valid_gen,
    epochs=10
)

y_pred = inception_model.predict(X_val)

Epoch 1/10
145/145 [==============================] - 121s 732ms/step - loss: 0.3418 - auc: 0.6263 - precision: 0.1214 - recall: 0.0050 - Accuracy: 0.0933 - val_loss: 0.4527 - val_auc: 0.6026 - val_precision: 0.2045 - val_recall: 0.0047 - val_Accuracy: 0.0788
Epoch 2/10
145/145 [==============================] - 78s 540ms/step - loss: 0.3327 - auc: 0.6530 - precision: 0.3667 - recall: 0.0014 - Accuracy: 0.0957 - val_loss: 0.3573 - val_auc: 0.6269 - val_precision: 0.2296 - val_recall: 0.0611 - val_Accuracy: 0.1013
Epoch 3/10
145/145 [==============================] - 77s 533ms/step - loss: 0.3309 - auc: 0.6590 - precision: 0.4809 - recall: 0.0082 - Accuracy: 0.0998 - val_loss: 0.3371 - val_auc: 0.6476 - val_precision: 0.6000 - val_recall: 0.0031 - val_Accuracy: 0.0900
Epoch 4/10
145/145 [==============================] - 78s 540ms/step - loss: 0.3294 - auc: 0.6643 - precision: 0.4453 - recall: 0.0074 - Accuracy: 0.1037 - val_loss: 0.3788 - val_auc: 0.5945 - val_precision: 0.1447 - val_r

In [3]:
import numpy as np

for label, p_count, t_count in zip(labels, 100 * np.mean(y_pred, 0), 100 * np.mean(y_val, 0)):
    print('%s: actual: %2.2f%%, predicted: %2.2f%%' % (label, t_count, p_count))

Atelectasis: actual: 16.54%, predicted: 15.86%
Cardiomegaly: actual: 9.09%, predicted: 12.87%
Consolidation: actual: 9.78%, predicted: 14.53%
Edema: actual: 9.44%, predicted: 24.20%
Effusion: actual: 17.66%, predicted: 19.34%
Emphysema: actual: 9.09%, predicted: 10.16%
Fibrosis: actual: 8.92%, predicted: 3.10%
Hernia: actual: 3.98%, predicted: 1.04%
Infiltration: actual: 25.54%, predicted: 40.66%
Mass: actual: 9.96%, predicted: 9.30%
No Finding: actual: 8.66%, predicted: 5.75%
Nodule: actual: 10.39%, predicted: 10.35%
Pleural_Thickening: actual: 8.40%, predicted: 5.56%
Pneumonia: actual: 8.92%, predicted: 10.42%
Pneumothorax: actual: 10.82%, predicted: 6.92%
