In [1]:
from tensorflow.keras.applications import MobileNet
import tensorflow as tf
from data_proccessing import image_size, labels

mnet = MobileNet(
        input_shape=(image_size, image_size, 3),
        weights='imagenet',
        include_top=False
    )
mnet.trainable = True

mnet_model = tf.keras.Sequential([
    mnet,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(len(labels), activation='sigmoid')])

mnet_model.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics=['AUC','Precision','Recall'])

d:\adl\data_proccessing.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_new = pd.concat([df_new, data_entry[data_entry[l]==1][:500]], ignore_index=True)


Found 4620 validated image filenames belonging to 15 classes.
Found 1155 validated image filenames belonging to 15 classes.
[[[[0.1137255  0.1137255  0.1137255 ]
   [0.1137255  0.1137255  0.1137255 ]
   [0.10980393 0.10980393 0.10980393]
   ...
   [0.18823531 0.18823531 0.18823531]
   [0.21960786 0.21960786 0.21960786]
   [0.33333334 0.33333334 0.33333334]]

  [[0.10980393 0.10980393 0.10980393]
   [0.1137255  0.1137255  0.1137255 ]
   [0.10980393 0.10980393 0.10980393]
   ...
   [0.18039216 0.18039216 0.18039216]
   [0.21568629 0.21568629 0.21568629]
   [0.31764707 0.31764707 0.31764707]]

  [[0.1137255  0.1137255  0.1137255 ]
   [0.10980393 0.10980393 0.10980393]
   [0.10980393 0.10980393 0.10980393]
   ...
   [0.18823531 0.18823531 0.18823531]
   [0.21176472 0.21176472 0.21176472]
   [0.29803923 0.29803923 0.29803923]]

  ...

  [[0.6901961  0.6901961  0.6901961 ]
   [0.6862745  0.6862745  0.6862745 ]
   [0.68235296 0.68235296 0.68235296]
   ...
   [0.13725491 0.13725491 0.13725491]

In [2]:
from sklearn.metrics import roc_curve, auc, roc_auc_score, accuracy_score, average_precision_score
from data_proccessing import train_gen, valid_gen, X_val, y_val

history = mnet_model.fit(train_gen,
              validation_data = valid_gen,
              epochs = 10,)

y_pred = mnet_model.predict(X_val)

Epoch 1/10


c:\Users\mandi\anaconda3\envs\adl\lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


145/145 ━━━━━━━━━━━━━━━━━━━━ 340s 2s/step - AUC: 0.6297 - Precision: 0.2203 - Recall: 0.0608 - loss: 0.3739 - val_AUC: 0.5732 - val_Precision: 0.0000e+00 - val_Recall: 0.0000e+00 - val_loss: 0.8864
Epoch 2/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 265s 2s/step - AUC: 0.7285 - Precision: 0.5110 - Recall: 0.0637 - loss: 0.3122 - val_AUC: 0.6570 - val_Precision: 0.2685 - val_Recall: 0.0357 - val_loss: 0.4120
Epoch 3/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 249s 2s/step - AUC: 0.7561 - Precision: 0.5485 - Recall: 0.0808 - loss: 0.3032 - val_AUC: 0.6674 - val_Precision: 0.6154 - val_Recall: 0.0041 - val_loss: 0.4018
Epoch 4/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 244s 2s/step - AUC: 0.7730 - Precision: 0.5487 - Recall: 0.0954 - loss: 0.2969 - val_AUC: 0.6722 - val_Precision: 0.4348 - val_Recall: 0.0052 - val_loss: 0.4040
Epoch 5/10
145/145 ━━━━━━━━━━━━━━━━━━━━ 242s 2s/step - AUC: 0.7864 - Precision: 0.5692 - Recall: 0.0996 - loss: 0.2909 - val_AUC: 0.7084 - val_Precision: 0.4249 - val_Recall: 0.0953 - val_loss: 0.330

In [3]:
import numpy as np
for label, p_count, t_count in zip(labels,
                                     100 * np.mean(y_pred, 0),
                                     100 * np.mean(y_val, 0)):
    print('%s: actual: %2.2f%%, predicted: %2.2f%%' % (label, t_count, p_count))

Atelectasis: actual: 16.54%, predicted: 20.60%
Cardiomegaly: actual: 9.09%, predicted: 0.97%
Consolidation: actual: 9.78%, predicted: 48.25%
Edema: actual: 9.44%, predicted: 4.86%
Effusion: actual: 17.66%, predicted: 22.79%
Emphysema: actual: 9.09%, predicted: 4.13%
Fibrosis: actual: 8.92%, predicted: 1.61%
Hernia: actual: 3.98%, predicted: 0.58%
Infiltration: actual: 25.54%, predicted: 43.22%
Mass: actual: 9.96%, predicted: 4.40%
No Finding: actual: 8.66%, predicted: 3.93%
Nodule: actual: 10.39%, predicted: 3.42%
Pleural_Thickening: actual: 8.40%, predicted: 3.35%
Pneumonia: actual: 8.92%, predicted: 10.86%
Pneumothorax: actual: 10.82%, predicted: 8.08%
