In [1]:
from tensorflow.keras.applications import MobileNet
import tensorflow as tf
from data_proccessing import image_size, labels

mnet = MobileNet(
        input_shape=(image_size, image_size, 3),
        weights='imagenet',
        include_top=False
    )
mnet.trainable = True

mnet_model = tf.keras.Sequential([
    mnet,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(len(labels), activation='sigmoid')])

mnet_model.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics=['AUC','Precision','Recall', 'Accuracy'])

d:\adl\data_proccessing.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_new = pd.concat([df_new, data_entry[data_entry[l]==1][:500]], ignore_index=True)


Found 4620 validated image filenames belonging to 15 classes.
Found 1155 validated image filenames belonging to 15 classes.
[[[[0.14117648 0.14117648 0.14117648]
   [0.13725491 0.13725491 0.13725491]
   [0.12941177 0.12941177 0.12941177]
   ...
   [0.12941177 0.12941177 0.12941177]
   [0.16078432 0.16078432 0.16078432]
   [0.20392159 0.20392159 0.20392159]]

  [[0.13333334 0.13333334 0.13333334]
   [0.13333334 0.13333334 0.13333334]
   [0.12941177 0.12941177 0.12941177]
   ...
   [0.12156864 0.12156864 0.12156864]
   [0.14901961 0.14901961 0.14901961]
   [0.19607845 0.19607845 0.19607845]]

  [[0.13333334 0.13333334 0.13333334]
   [0.13333334 0.13333334 0.13333334]
   [0.1254902  0.1254902  0.1254902 ]
   ...
   [0.11764707 0.11764707 0.11764707]
   [0.15294118 0.15294118 0.15294118]
   [0.18823531 0.18823531 0.18823531]]

  ...

  [[0.6666667  0.6666667  0.6666667 ]
   [0.7058824  0.7058824  0.7058824 ]
   [0.7058824  0.7058824  0.7058824 ]
   ...
   [0.16078432 0.16078432 0.16078432]

In [2]:
from data_proccessing import train_gen, valid_gen, X_val, y_val

history = mnet_model.fit(train_gen,
              validation_data = valid_gen,
              epochs = 10,)

y_pred = mnet_model.predict(X_val)

Epoch 1/10
145/145 [==============================] - 113s 734ms/step - loss: 0.3440 - auc: 0.6632 - precision: 0.2910 - recall: 0.0487 - Accuracy: 0.1498 - val_loss: 0.9703 - val_auc: 0.5515 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_Accuracy: 0.0978
Epoch 2/10
145/145 [==============================] - 74s 512ms/step - loss: 0.3115 - auc: 0.7342 - precision: 0.5051 - recall: 0.0644 - Accuracy: 0.2113 - val_loss: 0.4720 - val_auc: 0.6502 - val_precision: 0.3380 - val_recall: 0.0502 - val_Accuracy: 0.0926
Epoch 3/10
145/145 [==============================] - 84s 577ms/step - loss: 0.3011 - auc: 0.7601 - precision: 0.5589 - recall: 0.0818 - Accuracy: 0.2411 - val_loss: 0.4155 - val_auc: 0.6529 - val_precision: 0.6429 - val_recall: 0.0047 - val_Accuracy: 0.1810
Epoch 4/10
145/145 [==============================] - 83s 573ms/step - loss: 0.2961 - auc: 0.7736 - precision: 0.5838 - recall: 0.0951 - Accuracy: 0.2615 - val_loss: 0.3665 - val_auc: 0.6982 - val_precision: 0.5000

In [ ]:
import numpy as np
for label, p_count, t_count in zip(labels,
                                     100 * np.mean(y_pred, 0),
                                     100 * np.mean(y_val, 0)):
    print('%s: actual: %2.2f%%, predicted: %2.2f%%' % (label, t_count, p_count))

Atelectasis: actual: 16.54%, predicted: 20.60%
Cardiomegaly: actual: 9.09%, predicted: 0.97%
Consolidation: actual: 9.78%, predicted: 48.25%
Edema: actual: 9.44%, predicted: 4.86%
Effusion: actual: 17.66%, predicted: 22.79%
Emphysema: actual: 9.09%, predicted: 4.13%
Fibrosis: actual: 8.92%, predicted: 1.61%
Hernia: actual: 3.98%, predicted: 0.58%
Infiltration: actual: 25.54%, predicted: 43.22%
Mass: actual: 9.96%, predicted: 4.40%
No Finding: actual: 8.66%, predicted: 3.93%
Nodule: actual: 10.39%, predicted: 3.42%
Pleural_Thickening: actual: 8.40%, predicted: 3.35%
Pneumonia: actual: 8.92%, predicted: 10.86%
Pneumothorax: actual: 10.82%, predicted: 8.08%
